use_frameworks!

target 'test_Example', :exclusive => true do
  pod 'test', :path => '../'
  pod 'ZLSwipeableViewSwift'
  pod 'Cartography'
  pod 'ReactiveUI'
  pod 'AFNetworking', '~> 2.5'
  pod 'BDBOAuth1Manager'
  pod 'SwiftSVG'
  pod 'SwiftLocation'
  pod 'UIColor+FlatColors'
  pod 'NVActivityIndicatorView'
  pod 'Alamofire'

end

target 'test_Tests', :exclusive => true do
  pod 'test', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
